name: Test GitHub Actions

on:
  workflow_dispatch:
    # This allows manual triggering

jobs:
  test-clone-and-modify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone another repository
      run: |
        git clone https://github.com/ooospooky/apple-accessories.git /tmp/apple-accessories

    - name: Modify README, commit, and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd /tmp/apple-accessories
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b test-text
        echo "This is a new line added by GitHub Actions" | cat - README.md > temp && mv temp README.md
        git add README.md
        git commit -m "feat: add text in readme"
        git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/ooospooky/apple-accessories.git" HEAD:test-text -f
