name: Test GitHub Actions
on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input parameter'
        required: true
      input2:
        description: 'Second input parameter'
        required: true
      image_path:
        description: 'Path to the local image file'
        required: true

jobs:
  test-clone-and-modify:
    runs-on: ubuntu-latest
    permissions:               
      contents: write          
      pull-requests: write  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Upload local image
      id: upload-image
      uses: actions/upload-artifact@v2
      with:
        name: user-image
        path: ${{ github.event.inputs.image_path }}

    - name: Download uploaded image
      uses: actions/download-artifact@v2
      with:
        name: user-image
        path: downloaded-image

    - name: Clone another repository
      run: |
        git clone https://github.com/ooospooky/apple-accessories.git /tmp/apple-accessories

    - name: Modify README, commit, and push
      run: |
        cd /tmp/apple-accessories
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b test-text
        echo "This is a new line added by GitHub Actions!!" | cat - README.md > temp && mv temp README.md
        # Here you can use the downloaded image
        # For example, you could copy it to the repository:
        cp $GITHUB_WORKSPACE/downloaded-image/* .
        git add README.md
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "feat: add text in readme"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/ooospooky/apple-accessories.git
          git push origin test-text
        fi
