name: Test GitHub Actions

on:
  workflow_dispatch:
    # This allows manual triggering

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         echo "test the manual.yml on log"
